name: Generate CV PDFs

on:
  push:
    branches:
      - main
    paths:
      - "cv-*.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies for WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip libcairo2 libpango-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown weasyprint

      - name: Generate PDFs from Markdown
        run: |
          python generate_pdf.py

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CV-PDFs
          path: "*.pdf"

      - name: Create Release and Upload PDFs
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "cv-pdfs-${{ github.run_number }}"
          name: "CV PDFs - Run #${{ github.run_number }}"
          body: "Automatically generated CV PDFs from Markdown files"
          files: "*.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
